### ISSUE TITLE
Is there a license for this repo?

### ISSUE THREAD

**Issue by saintaardvark** [georgeslabreche/opssat-smartcam-map#5]
Hi there -- I came across this repo while looking into OPS-SAT, and I really like it -- the map itself is quite useful, and as a Javascript/Leaflet newbie it was quite instructive to read the code.

Is there a license for this repo?  I would really like to be able to be able to use this as a base for other things, but I don't want to step on any toes.

Thanks again for publishing this!

**Comment by georgeslabreche** [comment]
@saintaardvark thank you for raising this issue, it's an omission from my part. I've applied the MIT License!

**Comment by saintaardvark** [comment]
Thanks very much -- I appreciate your generosity!
